agent/run.sh

Just a minor tweak from the Saturday's debug session. It may help with debugging later if needed, so I decided to post it. Will do the same for the Jenkins Docker Image

Add a "DEBUG" flag to simplify debugging of agents in Docker

---

Dockerfile
plugin/pom.xml
pom.xml

JIRA task: [JENKINS-52190](https://issues.jenkins-ci.org/browse/JENKINS-52190)

[JENKINS-52190] Update Remoting Kafka to the released versions of Remoting/Core with extensibility API

---

agent/src/main/java/io/jenkins/plugins/remotingkafka/Agent.java
agent/src/main/java/io/jenkins/plugins/remotingkafka/Engine.java
agent/src/main/java/io/jenkins/plugins/remotingkafka/Options.java
kafka-client-lib/src/main/java/io/jenkins/plugins/remotingkafka/KafkaClientListener.java
kafka-client-lib/src/main/java/io/jenkins/plugins/remotingkafka/KafkaConfigs.java
kafka-client-lib/src/main/java/io/jenkins/plugins/remotingkafka/KafkaUtils.java
kafka-client-lib/src/main/java/io/jenkins/plugins/remotingkafka/builder/KafkaTransportBuilder.java
kafka-client-lib/src/main/java/io/jenkins/plugins/remotingkafka/commandtransport/KafkaClassicCommandTransport.java
kafka-client-lib/src/test/java/io/jenkins/plugins/remoting/kafka/builder/KafkaClassicCommandTransportBuilderTest.java
plugin/src/main/java/io/jenkins/plugins/remotingkafka/KafkaComputerLauncher.java
plugin/src/main/java/io/jenkins/plugins/remotingkafka/KafkaSecretManager.java
plugin/src/main/resources/io/jenkins/plugins/remotingkafka/KafkaComputerLauncher/main.jelly

JIRA task: [JENKINS-51470](https://issues.jenkins-ci.org/browse/JENKINS-51470)
Tasks:
@oleg-nenashev @Supun94 @dwnusbaum @jeffret-b

[JENKINS-51470] Provide connection security for Kafka master-agent connection

---

agent/pom.xml
kafka-client-lib/pom.xml
plugin/pom.xml
pom.xml

JIRA task: [JENKINS-51720](https://issues.jenkins-ci.org/browse/JENKINS-51720)

[JENKINS-51720] Update pom for alpha release

---

pom.xml

JIRA task: [JENKINS-52243](https://issues.jenkins-ci.org/browse/JENKINS-52243)

[JENKINS-52243] Update wiki page url in parent pom

---

CHANGELOG.md

JIRA task: [JENKINS-52242](https://issues.jenkins-ci.org/browse/JENKINS-52242)

[JENKINS-52242] Create changelog for remoting-kafka-plugin

---

README.md
docker-compose.yml

JIRA task: [JENKINS-52244](https://issues.jenkins-ci.org/browse/JENKINS-52244)
This PR is mergeable after https://github.com/jenkinsci/remoting-kafka-plugin/pull/16 and https://github.com/jenkinsci/remoting-kafka-plugin/pull/18 are approved.

[JENKINS-52244] Update README about alpha release

---

docker-compose.yml

JIRA task: [JENKINS-52044](https://issues.jenkins-ci.org/browse/JENKINS-52044)

[JENKINS-52044] Remove JNLP agent port from the Remoting Kafka Plugin demo

---

docker-compose.yml

This is a follow-up of https://github.com/jenkinsci/remoting-kafka-plugin/pull/23 because we changed the location of jenkins Dockerfile.
@oleg-nenashev

[Fix] Fix build in docker-compose

---

kafka-client-lib/src/main/java/io/jenkins/plugins/remotingkafka/commandtransport/KafkaClassicCommandTransport.java
plugin/src/main/java/io/jenkins/plugins/remotingkafka/KafkaSecretManager.java

JIRA task: [JENKINS-52422](https://issues.jenkins-ci.org/browse/JENKINS-52422)
Set logging level of sent and received commands to FINE.
@oleg-nenashev @Supun94 @dwnusbaum @jeffret-b

[JENKINS-52422] Remove diagnostics logging of events

---

Makefile
docker-compose.yml

A follow-up of https://github.com/jenkinsci/remoting-kafka-plugin/pull/27

Use remoting-kafka-agent image in docker-compose

---

CHANGELOG.md

JIRA task: [JENKINS-52621](https://issues.jenkins-ci.org/browse/JENKINS-52621)
@oleg-nenashev

[JENKINS-52621] Add changelog for 1.0 release

---

README.md

- Update plugin description.
- Remove `make stop` from README.
- Remove instructions to run in alpha release.
@oleg-nenashev

Update README for 1.0 release

---

docs/DOCUMENTATION.md

Fix 404 errors of relative links.

Fix relative links

---

CHANGELOG.md

Add changelog for version 1.1

---

plugin/pom.xml
pom.xml

JIRA task: [JENKINS-53416](https://issues.jenkins-ci.org/browse/JENKINS-53416)
Related issue: [JENKINS-53397](https://issues.jenkins-ci.org/browse/JENKINS-53397)
@oleg-nenashev @fnaum

[JENKINS-53416] Update remoting 3.26

---

README.md
docs/CONTRIBUTING.md

Time to update the project after GSoC with new contributing doc and JIRA epic issue: https://issues.jenkins-ci.org/browse/JENKINS-53417
@oleg-nenashev

Update README and contributing doc

---

pom.xml

@oleg-nenashev , after this update I will release 1.1.1

Upgrade remoting to 3.26

---

CHANGELOG.md

Add changelog for release 1.1.1

---

plugin/pom.xml

JIRA issue: [JENKINS-54173](https://issues.jenkins-ci.org/browse/JENKINS-54173)

[JENKINS-54173] Update common-compress to 1.18

---

kafka-client-lib/src/main/java/io/jenkins/plugins/remotingkafka/builder/ConsumerPropertiesBuilder.java
kafka-client-lib/src/main/java/io/jenkins/plugins/remotingkafka/builder/ProducerPropertiesBuilder.java

From **bootsrap** to **bootstrap**

Fix variable name typos
